# Generated by Django 4.2 on 2025-12-08 12:08

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(db_index=True, help_text='Historical site name in English', max_length=255, verbose_name='Site Name (English)')),
                ('name_ga', models.CharField(blank=True, help_text='Historical site name in Irish (Gaeilge)', max_length=255, verbose_name='Site Name (Irish)')),
                ('description_en', models.TextField(help_text='Detailed description in English', verbose_name='Description (English)')),
                ('description_ga', models.TextField(blank=True, help_text='Detailed description in Irish', verbose_name='Description (Irish)')),
                ('location', django.contrib.gis.db.models.fields.PointField(dim=3, help_text='Site coordinates (WGS84) with elevation', srid=4326, verbose_name='Location')),
                ('elevation_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation above sea level in meters', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(2000)], verbose_name='Elevation (m)')),
                ('site_type', models.CharField(choices=[('castle', 'Castle'), ('monastery', 'Monastery/Abbey'), ('fort', 'Fort/Ringfort'), ('burial_site', 'Burial Site/Tomb'), ('stone_monument', 'Stone Monument'), ('holy_well', 'Holy Well'), ('battlefield', 'Battlefield'), ('historic_house', 'Historic House'), ('archaeological_site', 'Archaeological Site'), ('church', 'Church/Chapel'), ('tower', 'Tower/Round Tower'), ('bridge', 'Historic Bridge'), ('other', 'Other')], db_index=True, help_text='Type of historical site', max_length=50, verbose_name='Site Type')),
                ('significance_level', models.IntegerField(default=2, help_text='1=Local, 2=Regional, 3=National, 4=International', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Significance Level')),
                ('date_established', models.DateField(blank=True, help_text='Date site was established', null=True, verbose_name='Date Established')),
                ('date_abandoned', models.DateField(blank=True, help_text='Date site was abandoned/destroyed', null=True, verbose_name='Date Abandoned')),
                ('construction_period', models.CharField(blank=True, help_text="Historical period description (e.g., 'Early Medieval')", max_length=100, verbose_name='Construction Period')),
                ('preservation_status', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('ruins', 'Ruins'), ('archaeological', 'Archaeological Only')], help_text='Current preservation state', max_length=50, verbose_name='Preservation Status')),
                ('unesco_site', models.BooleanField(default=False, help_text='Designated as UNESCO World Heritage Site', verbose_name='UNESCO World Heritage Site')),
                ('national_monument', models.BooleanField(db_index=True, default=False, help_text='Designated as National Monument', verbose_name='National Monument')),
                ('is_public_access', models.BooleanField(default=True, help_text='Site is accessible to public', verbose_name='Public Access')),
                ('visitor_center', models.BooleanField(default=False, help_text='Has visitor center or information point', verbose_name='Visitor Center')),
                ('admission_required', models.BooleanField(default=False, help_text='Admission fee required', verbose_name='Admission Required')),
                ('address', models.TextField(blank=True, help_text='Physical address or location description', verbose_name='Address')),
                ('eircode', models.CharField(blank=True, help_text='Irish postal code', max_length=10, verbose_name='Eircode')),
                ('website_url', models.URLField(blank=True, help_text='Official website URL', max_length=500, verbose_name='Website URL')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Username who created this record', max_length=100, null=True, verbose_name='Created By')),
                ('modified_by', models.CharField(blank=True, help_text='Username who last modified this record', max_length=100, null=True, verbose_name='Modified By')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Content moderation status', max_length=20, verbose_name='Approval Status')),
                ('approved_by', models.CharField(blank=True, help_text='Username who approved this site', max_length=100, null=True, verbose_name='Approved By')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, help_text='Source of site information', max_length=255, verbose_name='Data Source')),
                ('data_quality', models.IntegerField(default=3, help_text='Quality rating: 1=Poor, 5=Excellent', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Data Quality')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times site has been viewed', verbose_name='View Count')),
            ],
            options={
                'verbose_name': 'Historical Site',
                'verbose_name_plural': 'Historical Sites',
                'db_table': 'historical_site',
                'ordering': ['-significance_level', 'name_en'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(help_text='URL to image file', max_length=500, verbose_name='Image URL')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_ga', models.CharField(blank=True, max_length=255, verbose_name='Title (Irish)')),
                ('caption_en', models.TextField(blank=True, verbose_name='Caption (English)')),
                ('caption_ga', models.TextField(blank=True, verbose_name='Caption (Irish)')),
                ('photographer', models.CharField(blank=True, help_text='Name of photographer/creator', max_length=255, verbose_name='Photographer')),
                ('photo_date', models.DateField(blank=True, db_column='photo_date', help_text='Date photograph was taken', null=True, verbose_name='Date Taken')),
                ('copyright_info', models.CharField(blank=True, db_column='copyright_info', help_text='Copyright information', max_length=255, verbose_name='Copyright Info')),
                ('mime_type', models.CharField(blank=True, db_column='mime_type', help_text='Image MIME type (e.g., image/jpeg)', max_length=50, verbose_name='MIME Type')),
                ('alt_text', models.CharField(blank=True, db_column='alt_text', help_text='Accessibility alt text', max_length=255, verbose_name='Alt Text')),
                ('image_path', models.CharField(blank=True, db_column='image_path', help_text='Local file path for image', max_length=500, verbose_name='Image Path')),
                ('thumbnail_url', models.URLField(blank=True, db_column='thumbnail_url', help_text='URL to thumbnail image', max_length=500, verbose_name='Thumbnail URL')),
                ('is_public', models.BooleanField(db_column='is_public', default=True, help_text='Image is public', verbose_name='Public')),
                ('width_px', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width (pixels)')),
                ('height_px', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (pixels)')),
                ('file_size_kb', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='File Size (KB)')),
                ('is_primary', models.BooleanField(default=False, help_text='Use as main site image', verbose_name='Primary Image')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('license_type', models.CharField(blank=True, db_column='license_type', default='All Rights Reserved', help_text='Copyright/license information', max_length=50, verbose_name='License Type')),
                ('uploaded_by', models.CharField(blank=True, help_text='Username who uploaded this image', max_length=100, null=True, verbose_name='Uploaded By')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'db_table': 'site_image',
                'ordering': ['display_order', '-is_primary', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('journal', 'Journal Article'), ('website', 'Website'), ('archive', 'Archive Document'), ('oral_history', 'Oral History'), ('government_record', 'Government Record')], max_length=50, verbose_name='Source Type')),
                ('title', models.CharField(help_text='Full title of source', max_length=500, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Author(s)')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Publisher')),
                ('url', models.URLField(blank=True, help_text='Link to online source', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('isbn', models.CharField(blank=True, help_text='ISBN for books', max_length=20, verbose_name='ISBN')),
                ('pages', models.CharField(blank=True, db_column='pages', help_text='Relevant page numbers', max_length=50, verbose_name='Page Numbers')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about source', verbose_name='Notes')),
                ('reliability_score', models.IntegerField(default=3, help_text='1=Questionable, 5=Highly reliable', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Reliability Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, help_text='Username who added this source', max_length=100, null=True, verbose_name='Added By')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Historical Source',
                'verbose_name_plural': 'Historical Sources',
                'db_table': 'site_source',
                'ordering': ['-reliability_score', '-publication_year'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key for anonymous user tracking', max_length=40, verbose_name='Session Key')),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist - Want to Visit'), ('visited', 'Visited - Completed')], db_index=True, default='wishlist', help_text='Current status of bucket list item', max_length=20, verbose_name='Status')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When item was added to bucket list', verbose_name='Added At')),
                ('visited_at', models.DateTimeField(blank=True, help_text='When user marked site as visited', null=True, verbose_name='Visited At')),
                ('photo', models.ImageField(blank=True, help_text="User's photo from visit", null=True, upload_to='bucket_photos/', verbose_name='Photo')),
                ('photo_caption', models.TextField(blank=True, help_text="User's notes or caption about their visit", verbose_name='Photo Caption')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag', verbose_name='Is Deleted')),
                ('site', models.ForeignKey(db_column='site_id', help_text='Site on bucket list', on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list_items', to='sites.historicalsite', verbose_name='Historical Site')),
            ],
            options={
                'verbose_name': 'Bucket List Item',
                'verbose_name_plural': 'Bucket List Items',
                'db_table': 'bucket_list_item',
                'ordering': ['-added_at'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['session_key', 'status'], name='bucket_list_session_a7452b_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['site', 'session_key'], name='bucket_list_site_id_68fdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='bucketlistitem',
            index=models.Index(fields=['status'], name='bucket_list_status_646c9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='bucketlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('site', 'session_key'), name='unique_active_bucket_item'),
        ),
    ]
