"""
API URL routing

This sets up all the API endpoints using Django REST Framework's router.
The router automatically creates URLs for all the ViewSet actions. All
endpoints are under /api/v1/ for versioning.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    HistoricalSiteViewSet,
    ProvinceViewSet,
    CountyViewSet,
    HistoricalEraViewSet,
    SiteImageViewSet,
    BucketListViewSet,
)

# Create the router and register all the viewsets
# The router automatically creates URLs for list, detail, and custom actions
router = DefaultRouter()
router.register(r'sites', HistoricalSiteViewSet, basename='site')
router.register(r'provinces', ProvinceViewSet, basename='province')
router.register(r'counties', CountyViewSet, basename='county')
router.register(r'eras', HistoricalEraViewSet, basename='era')
router.register(r'images', SiteImageViewSet, basename='image')
router.register(r'bucket-list', BucketListViewSet, basename='bucket-list')

# All the URLs are generated by the router
urlpatterns = [
    path('', include(router.urls)),
]

# The router automatically creates these endpoints from the ViewSets:
#
# Sites:
#   GET /api/v1/sites/ - List all sites
#   GET /api/v1/sites/{id}/ - Get one site
#   GET /api/v1/sites/nearby/ - Find sites near a point
#   GET /api/v1/sites/in_bbox/ - Sites in a bounding box
#   GET /api/v1/sites/by_era/{era_id}/ - Filter by era
#   GET /api/v1/sites/by_county/{county_id}/ - Filter by county
#   GET /api/v1/sites/{id}/popup/ - Get popup data
#   GET /api/v1/sites/statistics/ - Get stats
#
# Provinces:
#   GET /api/v1/provinces/ - All province boundaries
#   GET /api/v1/provinces/{id}/ - One province
#   GET /api/v1/provinces/list_simple/ - Just names, no geometry
#
# Counties:
#   GET /api/v1/counties/ - All county boundaries
#   GET /api/v1/counties/{id}/ - One county
#   GET /api/v1/counties/list_simple/ - Just names
#   GET /api/v1/counties/by_province/{id}/ - Counties in a province
#
# Eras:
#   GET /api/v1/eras/ - All eras
#   GET /api/v1/eras/{id}/ - One era
#   GET /api/v1/eras/timeline/ - Eras with site counts
#
# Images:
#   GET /api/v1/images/ - All images
#   GET /api/v1/images/{id}/ - One image
#   GET /api/v1/images/by_site/{site_id}/ - Images for a site
#
# Bucket List:
#   GET /api/v1/bucket-list/ - User's bucket list
#   POST /api/v1/bucket-list/ - Add to bucket list
#   PATCH /api/v1/bucket-list/{id}/ - Update item
#   DELETE /api/v1/bucket-list/{id}/ - Remove item
